export type OpenSourceItem = {
  name: string;
  purpose: string;
  license: string;
  maintainer: string;
  homepage?: string;
  repository: string;
  version: string;
};

export type OpenSourceSection = {
  id: string;
  title: string;
  description: string;
  items: OpenSourceItem[];
};

export const openSourceSections: OpenSourceSection[] = [
  {
    id: "runtime",
    title: "运行时依赖",
    description: "这些项目直接参与页面渲染、交互、数据校验、数据库访问和服务运行。",
    items: [
      {
        name: "Next.js",
        purpose: "应用框架与页面路由",
        license: "MIT",
        maintainer: "Vercel",
        homepage: "https://nextjs.org",
        repository: "https://github.com/vercel/next.js",
        version: "16.2.1",
      },
      {
        name: "React",
        purpose: "界面组件与状态管理",
        license: "MIT",
        maintainer: "Meta React Team",
        homepage: "https://react.dev/",
        repository: "https://github.com/facebook/react",
        version: "19.2.0",
      },
      {
        name: "React DOM",
        purpose: "浏览器端渲染",
        license: "MIT",
        maintainer: "Meta React Team",
        homepage: "https://react.dev/",
        repository: "https://github.com/facebook/react",
        version: "19.2.0",
      },
      {
        name: "Tailwind CSS",
        purpose: "样式基础与工具类",
        license: "MIT",
        maintainer: "Tailwind Labs",
        homepage: "https://tailwindcss.com",
        repository: "https://github.com/tailwindlabs/tailwindcss",
        version: "4.2.2",
      },
      {
        name: "@tanstack/react-table",
        purpose: "猜测结果表格能力",
        license: "MIT",
        maintainer: "Tanner Linsley",
        homepage: "https://tanstack.com/table",
        repository: "https://github.com/TanStack/table",
        version: "8.21.3",
      },
      {
        name: "cmdk",
        purpose: "搜索候选与命令式输入体验",
        license: "MIT",
        maintainer: "Paco Coursey",
        homepage: "https://github.com/pacocoursey/cmdk#readme",
        repository: "https://github.com/pacocoursey/cmdk",
        version: "1.1.1",
      },
      {
        name: "motion",
        purpose: "轻量动效与过渡",
        license: "MIT",
        maintainer: "Matt Perry",
        repository: "https://github.com/motiondivision/motion",
        version: "12.38.0",
      },
      {
        name: "lucide-react",
        purpose: "图标资源",
        license: "ISC",
        maintainer: "Eric Fennis / Lucide Contributors",
        homepage: "https://lucide.dev",
        repository: "https://github.com/lucide-icons/lucide",
        version: "0.542.0",
      },
      {
        name: "clsx",
        purpose: "条件样式组合",
        license: "MIT",
        maintainer: "Luke Edwards",
        repository: "https://github.com/lukeed/clsx",
        version: "2.1.1",
      },
      {
        name: "tailwind-merge",
        purpose: "Tailwind 样式合并",
        license: "MIT",
        maintainer: "Dany Castillo",
        homepage: "https://github.com/dcastil/tailwind-merge",
        repository: "https://github.com/dcastil/tailwind-merge",
        version: "3.5.0",
      },
      {
        name: "zod",
        purpose: "配置与数据结构校验",
        license: "MIT",
        maintainer: "Colin McDonnell",
        homepage: "https://zod.dev",
        repository: "https://github.com/colinhacks/zod",
        version: "4.3.6",
      },
      {
        name: "drizzle-orm",
        purpose: "数据库访问层",
        license: "Apache-2.0",
        maintainer: "Drizzle Team",
        homepage: "https://orm.drizzle.team",
        repository: "https://github.com/drizzle-team/drizzle-orm",
        version: "0.44.7",
      },
      {
        name: "pg",
        purpose: "PostgreSQL 客户端",
        license: "MIT",
        maintainer: "Brian Carlson",
        homepage: "https://github.com/brianc/node-postgres",
        repository: "https://github.com/brianc/node-postgres",
        version: "8.20.0",
      },
      {
        name: "redis",
        purpose: "Redis 客户端与限流支撑",
        license: "MIT",
        maintainer: "Redis",
        homepage: "https://github.com/redis/node-redis",
        repository: "https://github.com/redis/node-redis",
        version: "5.11.0",
      },
    ],
  },
  {
    id: "tooling",
    title: "开发与构建工具",
    description: "这些项目用于类型检查、构建、测试、Lint 和数据脚本执行。",
    items: [
      {
        name: "TypeScript",
        purpose: "类型系统与脚本开发",
        license: "Apache-2.0",
        maintainer: "Microsoft",
        homepage: "https://www.typescriptlang.org/",
        repository: "https://github.com/microsoft/TypeScript",
        version: "5.9.3",
      },
      {
        name: "tsx",
        purpose: "本地脚本执行",
        license: "MIT",
        maintainer: "Hiroki Osame",
        homepage: "https://tsx.is",
        repository: "https://github.com/privatenumber/tsx",
        version: "4.21.0",
      },
      {
        name: "ESLint",
        purpose: "代码规范检查",
        license: "MIT",
        maintainer: "Nicholas C. Zakas / ESLint Team",
        homepage: "https://eslint.org",
        repository: "https://github.com/eslint/eslint",
        version: "9.39.4",
      },
      {
        name: "eslint-config-next",
        purpose: "Next.js 代码规范配置",
        license: "MIT",
        maintainer: "Vercel",
        homepage: "https://nextjs.org/docs/app/api-reference/config/eslint",
        repository: "https://github.com/vercel/next.js",
        version: "16.2.1",
      },
      {
        name: "Vitest",
        purpose: "测试框架",
        license: "MIT",
        maintainer: "Anthony Fu / Vitest Contributors",
        homepage: "https://github.com/vitest-dev/vitest#readme",
        repository: "https://github.com/vitest-dev/vitest",
        version: "3.2.4",
      },
      {
        name: "drizzle-kit",
        purpose: "数据库结构同步与工具链",
        license: "MIT",
        maintainer: "Drizzle Team",
        homepage: "https://orm.drizzle.team",
        repository: "https://github.com/drizzle-team/drizzle-orm",
        version: "0.31.10",
      },
      {
        name: "@tailwindcss/postcss",
        purpose: "Tailwind PostCSS 集成",
        license: "MIT",
        maintainer: "Tailwind Labs",
        homepage: "https://tailwindcss.com",
        repository: "https://github.com/tailwindlabs/tailwindcss",
        version: "4.2.2",
      },
      {
        name: "@types/node",
        purpose: "Node.js 类型定义",
        license: "MIT",
        maintainer: "DefinitelyTyped Contributors",
        homepage: "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node",
        repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
        version: "20.19.37",
      },
      {
        name: "@types/pg",
        purpose: "pg 类型定义",
        license: "MIT",
        maintainer: "DefinitelyTyped Contributors",
        homepage: "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pg",
        repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
        version: "8.20.0",
      },
      {
        name: "@types/react",
        purpose: "React 类型定义",
        license: "MIT",
        maintainer: "DefinitelyTyped Contributors",
        homepage: "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react",
        repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
        version: "19.2.14",
      },
      {
        name: "@types/react-dom",
        purpose: "React DOM 类型定义",
        license: "MIT",
        maintainer: "DefinitelyTyped Contributors",
        homepage: "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom",
        repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
        version: "19.2.3",
      },
    ],
  },
];
